In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [4]:
def add_row(A,k,i,j):
    "Add k times row j to row i in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [5]:
def scale_row(A,k,i):
    "Multiply row i by k in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [6]:
def switch_rows(A,i,j):
    "Switch rows i and j in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [11]:
K = np.array([[1, 2, -1], [2, -1, -1], [3, -4, -1]])

In [15]:
n = np.array([[8], [5], [2]])

In [22]:
L = np.hstack([K, n])
print(L)

[[ 1  2 -1  8]
 [ 2 -1 -1  5]
 [ 3 -4 -1  2]]


In [61]:
U = np.array([[1, -1, -1, 5], [1, 1, 1, 1], [5, -1, 2, 17]])
print(U)

[[ 1 -1 -1  5]
 [ 1  1  1  1]
 [ 5 -1  2 17]]


In [70]:
def solveMatrix(M):
    if M[0, 0] > 0:
        M1 = scale_row(M, 1/M[0, 0], 0)
        M2 = add_row(M1, -M[1, 0], 1, 0)
        M3 = add_row(M2, -M[2, 0], 2, 0)
        M4 = add_row(M3, -(M3[2, 1]/M3[1, 1]), 2, 1)
        print(M4)
        if M4[2,3] == 0:
            z = 0
            y = (M4[1, 3]-(M4[1, 2] * z)) / M4[1, 1]
            x = (M4[0, 3]-((M4[0, 1]* y) + (M4[0, 2] * z))/ M4[0,0]
            return (x, y, z)
        z = M4[2,3] / M4[2, 2]
        y = M4[1, 3]-(M4[1, 2] * z) / M4[1, 1]
        x = M4[0, 3]-((M4[0, 1]* y) + (M4[0, 2] * z))/ M4[0,0]
    return (x, y, z)

In [72]:
solveMatrix(L)

[[  1.   2.  -1.   8.]
 [  0.  -5.   1. -11.]
 [  0.   0.   0.   0.]]


(3.5999999999999996, 2.2, 0)